CREATE TABLE IF NOT EXISTS `Game` (
    id_game INT PRIMARY KEY AUTO_INCREMENT,
    correct_word VARCHAR(255) NOT NULL,
    client_agent VARCHAR(255) NOT NULL,
    client_ip VARCHAR(255) NOT NULL,
    create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `Try` (
    id_try INT PRIMARY KEY AUTO_INCREMENT,
    id_game INT NOT NULL,
    user_word VARCHAR(255) NOT NULL,
    is_correct BOOLEAN NOT NULL,
    number_try INT CHECK (number_try BETWEEN 1 AND 6),
    number_tips_used INT NOT NULL,
    create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_game) REFERENCES Game(id)
);